apiVersion: v1
kind: Service
metadata:
  name: svc-nlb-otel-gateway
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "obs-cluster-otel-gw"
    # Provisions a high-performance Network Load Balancer (NLB) in AWS
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance" # Allows SNAT and resolves VPC peering routing
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal" # Kept private inside the VPC
spec:
  type: LoadBalancer
  # Topology Aware Routing for Kubernetes 1.30+ (eliminates cross-AZ transfer fees)
  trafficDistribution: PreferSameZone
  selector:
    # Selects the Tier 2 Router pods managed by the OTel Operator
    app.kubernetes.io/name: otel-collector-tier2-router-collector
    app.kubernetes.io/managed-by: opentelemetry-operator
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
