apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-info-observability
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://github.example.internal/platform/observability-platform.git
      targetRevision: main
      path: observability-platform/dashboard-and-alert-generators/helm-chart
      helm:
        valueFiles:
          - $values/observability/product-info-values.yaml
    - repoURL: https://github.example.internal/apps/product-info-service.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
