name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GOLANG_APP_REPO: golang-product-service
  PYTHON_APP_REPO: python-product-info-service
  APPS_SRC_DIR: workloads/apps-src

jobs:
  build-and-push:
    name: Build & Push Images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ==============================================================================
      # Authenticate to Docker Hub using GitHub Repository Secrets:
      # - DOCKERHUB_USER_NAME
      # - DOCKERHUB_USER_TOKEN
      # ==============================================================================
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_USER_TOKEN }}

      # ==============================================================================
      # Build & Push Go Product Service
      # ==============================================================================
      - name: Build and Push Go Product Service
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.APPS_SRC_DIR }}/golang-app
          file: ./${{ env.APPS_SRC_DIR }}/golang-app/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USER_NAME }}/${{ env.GOLANG_APP_REPO }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USER_NAME }}/${{ env.GOLANG_APP_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ==============================================================================
      # Build & Push Python Product Info Service
      # ==============================================================================
      - name: Build and Push Python Product Info Service
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.APPS_SRC_DIR }}/python-app
          file: ./${{ env.APPS_SRC_DIR }}/python-app/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USER_NAME }}/${{ env.PYTHON_APP_REPO }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USER_NAME }}/${{ env.PYTHON_APP_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
